config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  authenticate :user do
    resources :files, controller: 'documents', as: 'documents' do
      get 'upgrade', on: :member
    end
    resources :folders
  end

  get 'home/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :files, controller: 'documents', as: 'documents'
      resources :folders
    end
  end

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'
  belongs_to :parent_folder, class_name: 'Folder', optional: true
  has_many :folders, class_name: 'Folder', foreign_key: 'parent_folder_id', inverse_of: :parent_folder
  has_many :documents, class_name: 'Document', foreign_key: 'parent_folder_id', inverse_of: :parent_folder
  validates_uniqueness_of :name, :scope => [:parent_folder_id, :created_by_id]
  validates :created_by, presence: true
  validates :updated_by, presence: true
  validates :name, presence: true, allow_blank: false
  validate :parent_folder_ownership

  before_destroy :has_contents?

  scope :in_root, -> () {where(parent_folder: nil)}
  scope :child_of, -> (parent_id=nil) {where(parent_folder_id: parent_id)}
  scope :is_owner, -> (owner) {where(created_by: owner)}
  scope :name_ilike, -> (name) { where('name ilike any ( array[?] )', name.map {|val| "%#{val}%"} ) }

  def full_path
    parent_folder.nil? ? "/#{name}" : "#{parent_folder.full_path}/#{name}"
  end

  private

  def parent_folder_ownership
    unless parent_folder.nil? or parent_folder.created_by == created_by
      errors[:parent_folder_ownership] << 'You don\'t have access to the parent folder.'
    end
  end

  def has_contents?
    unless folders.count.zero? and documents.count.zero?
      errors[:contents] << 'The Folder you\'re trying to delete has contents!.'
    end
    throw(:abort) unless errors.blank?
  end

  def force_delete
    documents.delete_all
    folders.each(&:force_delete)
    self.destroy
  end



end

app/controllers/api/v1/folders_controller.rb
require 'pp'
module Api
  module V1
    class FoldersController < APIController

      before_action only: [:index, :show] do
        doorkeeper_authorize! :read
      end

      before_action only: [:create, :update] do
        doorkeeper_authorize! :write
      end

      before_action only: [:destroy] do
        doorkeeper_authorize! :delete
      end
      before_action :set_folder, only: [:show, :update, :destroy]

      respond_to :json

      def index
        query_folders = Folder.is_owner(current_user.id)
        if folder_params.has_key? :name
          query_folders = query_folders.name_ilike(folder_params[:name].split(','))
        end
        if folder_params.has_key? :parent_folder_id
          parent_ids = folder_params[:parent_folder_id].split(',').map{|x| x=='-1' ? nil : x}
          query_folders = query_folders.child_of(parent_ids)
        end
        if folder_params.has_key? :limit
          query_folders = query_folders.limit(folder_params[:limit])
        end
        if folder_params.has_key? :offset
          query_folders = query_folders.offset(folder_params[:offset])
        end
        @folders = FolderDecorator.decorate_collection(query_folders)
      end

      def show
        @folder = @folder.decorate
      end

      def create
        if not folder_create.has_key?(:name)
          error_renderer({code: 400, message: 'Name parameter is missing'})
        else
          @folder = Folder.new(folder_create.merge({:created_by_id => 1,:updated_by_id => 1}))
          if @folder.save
            @folder = @folder.decorate
          else
            error_renderer(error_creator(@folder.errors))
          end
        end
      end

      def update
        if @folder.update(folder_create)
          @folder = @folder.decorate
        else
          error_renderer(error_creator(@folder.errors))
        end
      end

      def destroy
        if force_delete_param
          @folder.documents.destroy_all
          @folder.folders.each(&:force_delete)
        end

        if @folder.destroy
          head :no_content
        else
          error_renderer(error_creator(@folder.errors))
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_folder
        if Folder.exists?(params[:id])
          @folder = Folder.find(params[:id])
          unless current_user.id == @folder.created_by_id
            error_renderer({code: 401, message: 'Unauthorized'})
          end
        else
          error_renderer({code: 404, message: 'Folder Not Found'})
        end
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def folder_params
        temp = params.permit(:name, :id_parent_folder,:limit,:offset,:format)
        if temp.has_key? :id_parent_folder
          temp[:parent_folder_id] =  temp[:id_parent_folder]
          temp.delete(:id_parent_folder)
        end
        temp
      end

      def folder_create
        temp = params.permit(:name, :id_parent_folder)
        temp[:parent_folder_id] = temp.delete(:id_parent_folder)
        temp
      end

      def force_delete_param
        temp = params.permit(:force)
        (temp.has_key? :force and temp[:force] == '1')
      end

    end
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /folders
  # GET /folders.json
  def index
    folders = FolderDecorator.decorate_collection(Folder.is_owner(current_user.id).in_root)
    files = DocumentDecorator.decorate_collection(Document.is_owner(current_user.id).in_root)
    @contents = folders.map(&:to_simple_object) + files.map(&:to_simple_object)

    @current_folder = Folder.new(name: 'Root')
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @user = User.find_by id: @folder.created_by
    @contents = @folder.decorate.contents
  end

  # GET /folders/new
  def new
    @folder = Folder.new(:parent_folder_id => (folder_new_params) )
    @fixed = params.has_key? :parent_folder_id
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(name: folder_params[:name], parent_folder_id: folder_create_params, created_by: current_user, updated_by: current_user)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: "#{Folder.model_name.human} #{t('succesfully_created')}" }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: "#{Folder.model_name.human} #{t('succesfully_updated')}" }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: "#{Folder.model_name.human} #{t('succesfully_destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:name, :parent_folder_id)
    end

    def folder_new_params
      if params.has_key?(:parent_folder_id) and params[:parent_folder_id] != '-1'
        (params[:parent_folder_id])
      else
        nil
      end
    end

    def folder_create_params
      if folder_params.has_key?(:parent_folder_id) and folder_params[:parent_folder_id] != '-1'
        (folder_params[:parent_folder_id])
      else
        nil
      end
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_contents.erb
<div class="row">
  <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item", style="padding-bottom: 5%">
    <div class="card h-100 text-center">
      <div class="card-body">
        <h4 class="card-title"><%= current_folder.name %></h4>
        <p class="card-text">
          <% if current_folder.persisted? %>
              <b> <%= t('created') %> </b><%= current_folder.created_at%>
              <br>
              <b> <%= t('updated') %> </b><%= current_folder.updated_at%>
          <% end %>
        </p>
      </div>

      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to  "#{t('create')} #{t('folder.folder')} #{t('here')}", new_folder_path(:parent_folder_id => current_folder.persisted? ? current_folder.id : -1), html_options={class: 'btn btn-primary '} %>
        </li>
        <li class="list-group-item">
          <%= link_to "#{t('upload')} #{t('file')} #{t('here')}", new_document_path(:parent_folder_id => current_folder.persisted? ? current_folder.id : -1), html_options={class: 'btn btn-primary '} %>

      <% if current_folder.persisted? %>
          <li class="list-group-item">
            <%= link_to "#{t('editing')} #{t('folder.folder')}", edit_folder_path(current_folder), html_options={class: 'btn btn-primary '} %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>



<% contents.each_with_index do |folder, index| %>
    <% if index != 0 and (index + 1) % 4 == 0 %>
        </div>
        <div class="row">
    <% end %>


    <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item", style="padding-bottom: 5%">
      <div class="card h-100 text-center">
        <% if folder[:type].zero? %>
            <%= image_tag("file_icon.png", size: "100x100", :alt => "icon folder", class: 'mx-auto d-block') %>
        <% else %>
            <%= image_tag("folder_icon.jpg", size: "100x100", :alt => "icon folder", class: 'mx-auto d-block') %>
        <% end %>
        <div class="card-body">
          <h4 class="card-title">
            <%= link_to folder[:name], folder[:url]%>
          </h4>
          <p class="card-text">
            <b> <%= t('created') %> </b><%= folder[:created_at]%>
            <br>
            <b> <%= t('updated') %>  </b><%= folder[:updated_at]%>
          </p>
        </div>
      </div>
    </div>
<% end %>
</div>

app/views/folders/_form.html.erb
<%= simple_form_for(@folder) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <% if @fixed %>
        <% if @folder.parent_folder.nil? %>
            <%= f.association :parent_folder, collection: [] ,
                              :include_blank => '/',
                              :label_method => lambda { |parent| "#{parent.decorate.full_path}" } %>
        <% else %>
            <%= f.association :parent_folder,
                              collection: Folder.where(id: @folder.parent_folder_id),
                              :include_blank => false,
                              :label_method => lambda { |parent| "#{parent.decorate.full_path}" } %>
        <% end %>
    <% else %>
        <%= f.association :parent_folder,
                          :include_blank => '/',
                          collection: Folder.is_owner(current_user.id).where.not(id: @folder.id),
                          :label_method => lambda { |parent| "#{parent.decorate.full_path}" } %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1> <%= "#{t('editing')} #{t('document.document')}" %> </h1>

<%= render 'form', folder: @folder %>
<br>
<%= link_to t('show'), @folder %> |
<%= link_to t('back'), folders_path %>

app/views/folders/index.html.erb
<h1> <%= t('folder.folders') %> </h1>
<h2> <%= t('path') %> </h2>


<%= render 'contents', :contents=>@contents, :current_folder=>@current_folder %>

<br>

<%
=begin
  <!-- Pagination -->
<ul class="pagination justify-content-center">
<li class="page-item">
<a class="page-link" href="#" aria-label="Previous">
<span aria-hidden="true">&laquo;</span>
      <span class="sr-only">Previous</span>
  </a>
  </li>
  <li class="page-item">
<a class="page-link" href="#">1</a>
  </li>
  <li class="page-item">
<a class="page-link" href="#" aria-label="Next">
<span aria-hidden="true">&raquo;</span>
      <span class="sr-only">Next</span>
  </a>
  </li>
  </ul>
=end


%>

app/views/folders/new.html.erb
<h1> <%= "#{t('new')} #{t('folder.folder')}" %> </h1>

<%= render 'form', folder: @folder %>
<br>
<%= link_to t('back'), folders_path %>

app/views/folders/show.html.erb
<h2><%= t('path') %>  <%= @folder.full_path %></h2>
<br>


<%= render 'contents', :contents=>@contents, :current_folder=>@folder %>