config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  authenticate :user do
    resources :files, controller: 'documents', as: 'documents' do
      get 'upgrade', on: :member
    end
    resources :folders
  end

  get 'home/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :files, controller: 'documents', as: 'documents'
      resources :folders
    end
  end

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :parent_folder, class_name: 'Folder', optional: true
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'
  has_many :versions, dependent: :destroy

  validates_uniqueness_of :name, :scope => [:parent_folder_id, :created_by_id]
  validates :created_by, presence: true
  validates :updated_by, presence: true
  validates :name, presence: true, allow_blank: false
  validate :parent_folder_ownership

  scope :in_root, -> () {where(parent_folder: nil)}
  scope :child_of, -> (parent_id=nil) {where(parent_folder_id: parent_id)}
  scope :is_owner, -> (owner) {where(created_by: owner)}
  scope :name_ilike, -> (name) { where('name ilike any ( array[?] )', name.map {|val| "%#{val}%"} ) }

  attr_accessor :upfile

  after_initialize do
    @version = versions.count.zero? ? nil : latest_version.version
  end

  before_destroy :destroy_versions
  def access_url
    current_version.access_url
  end

  def expiration_date
    Time.now + 1.hour
  end

  def version
    if @version.nil?
      @version = versions.count.zero? ? nil : latest_version.version
    end
    @version
  end

  def version=(ver)
    unless available_versions.include? ver
      raise ArgumentError, 'The specified version does\' exist!'
    end
    @version = ver
  end

  def size
    current_version.size
  end

  def available_versions
    versions.pluck(:version)
  end

  def full_path
    parent_folder.nil? ? "/#{name}" : "#{parent_folder.full_path}/#{name}"
  end

  def parent_folder_ownership
    unless parent_folder.nil? or parent_folder.created_by == created_by
      errors[:parent_folder_ownership] << 'You don\'t have access to the parent folder.'
    end
  end

  def current_version
    versions.where(version: version).first
  end

  private

  def destroy_versions
    versions.destroy_all
  end



  def latest_version
    versions.where(current: true).order(version: :desc).first
  end
end

app/controllers/api/v1/documents_controller.rb
require 'pp'
module Api
  module V1
    class DocumentsController < APIController

      before_action only: [:index, :show] do
        doorkeeper_authorize! :read
      end

      before_action only: [:create, :update] do
        doorkeeper_authorize! :write
      end

      before_action only: [:destroy] do
        doorkeeper_authorize! :delete
      end
      before_action :set_document, only: [:show, :update, :destroy]
      respond_to :json

      def index
        query_documents = Document.is_owner(current_user.id)
        if document_params.has_key? :name
          query_documents = query_documents.name_ilike(document_params[:name].split(','))
        end
        if document_params.has_key? :parent_folder_id
          parent_ids = document_params[:parent_folder_id].split(',').map{|x| x=='-1' ? nil : x}
          query_documents = query_documents.child_of(parent_ids)
        end
        if document_params.has_key? :limit
          query_documents = query_documents.limit(document_params[:limit])
        end
        if document_params.has_key? :offset
          query_documents = query_documents.offset(document_params[:offset])
        end
        @documents = DocumentDecorator.decorate_collection(query_documents)
      end

      def show
        @document = @document.decorate
      end

      def create
        if not document_create.has_key? :upfile
          error_renderer({code:400, message: 'No file provided!'})
        elsif (document_create[:upfile].size) > 1024*(2.0**20)
          error_renderer({code:413, message: 'Uploaded File is too large, maximum size is 5 MB'})
        else
          name = (document_create.has_key?(:name) ? document_create[:name] : document_create[:upfile].original_filename)
          @document = Document.new(
              name: name,
              parent_folder_id: document_create[:parent_folder],
              created_by_id: current_user.id,
              updated_by_id: current_user.id
          )
          if @document.save
            @version = Version.new(
                                  document: @document,
                                  version: 1,
                                  size: (document_create[:upfile].size),
                                  current: true,
                                  upfile: document_create[:upfile],
                                  user: @document.created_by
            )
            if @version.save
              @document = @document.decorate
            else
              @document.destroy
              error_renderer(error_creator(@document.errors))
            end
          else
            error_renderer(error_creator(@document.errors))
          end
        end
      end

      def update
        if request.method_symbol == :put
          update_put
        elsif request.method_symbol == :patch
          update_patch
        else
          render partial: 'api/v1/error', locals: {:@error => {code: 501, message: 'Not Implemented'}}, status: 501
        end
      end

      def update_put
        old_version = @document.current_version
        @new_version = Version.new(
                              document: @document,
                              version: @document.version+1,
                              size: (document_create[:upfile].size/(2.0**20)).ceil,
                              current: true,
                              upfile: document_create[:upfile],
                              user: @document.created_by
        )
        if @new_version.save
          old_version.current = false
          old_version.save
          render :partial => 'api/v1/documents/document', locals: {document: Document.find(params[:id]).decorate}
        else
          error_renderer(error_creator(@document.errors))
        end
      end

      def update_patch
        if @document.update(:parent_folder => document_patch[:parent_folder])
          @document = @document.decorate
        else
          error_renderer(error_creator(@document.errors))
        end
      end

      def destroy
        if @document.destroy
          head :no_content
        else
          error_renderer(error_creator(@document.errors))
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_document
        if Document.exists?(params[:id])
          @document = Document.find(params[:id])
          unless current_user.id == @document.created_by_id
            error_renderer({code: 401, message: 'Unauthorized'})
          end
        else
          render partial: 'api/v1/error', locals: {:@error => {code: 404, message: 'Document Not Found'}}, status: 404
        end
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def document_params
        temp = params.permit(:name, :id_parent_folder,:limit,:offset,:format).to_hash.symbolize_keys
        if temp.has_key? :id_parent_folder
          temp[:parent_folder_id] =  temp[:id_parent_folder]
          temp.delete(:id_parent_folder)
        end
        temp
      end

      def document_create
        temp = params.permit(:name, :id_parent_folder, :upfile)
        temp[:parent_folder] = nil
        if temp.has_key?(:id_parent_folder) and Folder.exists?(id: temp[:id_parent_folder])
          temp[:parent_folder] = Folder.find(temp[:id_parent_folder])
          temp[:parent_folder_id] = temp.delete(:id_parent_folder)
        end
        temp
      end

      def document_patch
        temp = params.permit(:id_parent_folder)
        temp[:parent_folder] = nil
        if temp.has_key?(:id_parent_folder) and Folder.exists?(id: temp[:id_parent_folder])
          temp[:parent_folder] = Folder.find(temp[:id_parent_folder])
        end
        temp
      end

      def force_delete_param
        temp = params.permit(:force)
        (temp.has_key? :force and temp[:force] == 1)
      end

    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.is_owner(current_user.id)
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new(:parent_folder_id => (folder_new_params) )
    @fixed = params.has_key? :parent_folder_id
  end

  # GET /documents/1/edit
  def edit
  end

  # GET /documents/1/upgrade
  def upgrade
  end

  # POST /documents
  # POST /documents.json
  def create


    if not document_create.has_key? :upfile
      @document.errors.add(:upfile, t('document.error.upfile.missing'))
      @fixed = true
      render :new
    elsif (document_create[:upfile].size) > 1024*(2.0**20)
      @document.errors.add(:upfile, t('document.error.upfile.size'))
      @fixed = true
      render :new
    else
      name = (document_create[:name].blank? ? document_create[:upfile].original_filename : document_create[:name])
      @document = Document.new(name: name,
                               parent_folder_id: folder_create_params,
                               created_by: current_user,
                               updated_by: current_user)
      if @document.save
        @version = Version.new(
            document: @document,
            version: 1,
            size: (document_create[:upfile].size),
            current: true,
            upfile: document_create[:upfile],
            user: @document.created_by
        )
        if @version.save
          redirect_to @document, notice: "#{Document.model_name.human} #{t('succesfully_created')}"
        else
          @document.destroy
          @document = Document.new(name: document_params[:name],
                                   parent_folder_id: folder_create_params,
                                   created_by: current_user,
                                   updated_by: current_user)
          @document.errors[:base] << t('document.error.base')
          @fixed = true
          render :new
        end
      else
        @fixed = true
        render :new
      end
    end

  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    if request.request_method_symbol == :put
      update_put
    elsif request.request_method_symbol == :patch
      update_patch
    else
      render partial: 'api/v1/error', locals: {:@error => {code: 501, message: 'Not Implemented'}}, status: 501
    end


=begin
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  def update_put
    old_version = @document.current_version
    @new_version = Version.new(
        document: @document,
        version: @document.version+1,
        size: (document_create[:upfile].size/(2.0**20)).ceil,
        current: true,
        upfile: document_create[:upfile],
        user: @document.created_by
    )
    if @new_version.save
      old_version.current = false
      old_version.save
      redirect_to @document, notice: "#{t('new_f')} #{Version.model_name.human} #{t('succesfully_uploaded')}"
    else
      @document.errors.add(:upfile, @new_version.errors[:upfile][0])
      render :upgrade
    end
  end

  def update_patch
    if @document.update(:parent_folder_id => document_patch[:parent_folder_id])
      redirect_to @document, notice: "#{Document.model_name.human} #{t('succesfully_updated')}"
    else
      error_renderer(error_creator(@document.errors))
    end
  end


  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "#{Document.model_name.human} #{t('succesfully_destroyed')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
      if params.has_key? :version and @document.available_versions.include?(params[:version].to_i)
        @document.version = params[:version].to_i
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :parent_folder_id)
    end

    def folder_new_params
      if params.has_key?(:parent_folder_id) and params[:parent_folder_id] != '-1'
        (params[:parent_folder_id])
      else
        nil
      end
    end

    def folder_create_params
      if document_params.has_key?(:parent_folder_id) and document_params[:parent_folder_id] != '-1'
        (document_params[:parent_folder_id])
      else
        nil
      end
    end

    def document_create
      temp = params.require(:document).permit(:name, :parent_folder_id, :upfile)
      temp[:parent_folder] = nil
      if temp.has_key?(:parent_folder_id) and Folder.exists?(id: temp[:parent_folder_id])
        temp[:parent_folder] = Folder.find(temp[:parent_folder_id])
      end
      temp
    end

  def document_patch
    params.permit(:parent_folder_id)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for(@document,html: {:multipart => true }) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <% if @fixed %>
        <% if @document.parent_folder.nil? %>
            <%= f.association :parent_folder, collection: [] ,
                              :include_blank => '/',
                              :label_method => lambda { |parent| "#{parent.decorate.full_path}" } %>
        <% else %>
            <%= f.association :parent_folder,
                              collection: Folder.where(id: @document.parent_folder_id),
                              :include_blank => false,
                              :label_method => lambda { |parent| "#{parent.decorate.full_path}" } %>
        <% end %>
    <% else %>
        <%= f.association :parent_folder,
                          :include_blank => '/',
                          collection: Folder.is_owner(current_user.id),
                          :label_method => lambda { |parent| "#{parent.decorate.full_path}" } %>
    <% end %>
    <%= f.input :upfile, as: :file, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documents/_move_form.html.erb
<%= simple_form_for @document,html: {:multipart => true }, :method => :patch do |f| %>

  <div class="form-inputs">

    <%= f.association :parent_folder,
                      :include_blank => '/',
                      collection: Folder.is_owner(current_user.id),
                      :label_method => lambda { |parent| "#{parent.decorate.full_path}" } %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documents/_upgrade_form.html.erb
<%= simple_form_for @document,:url => document_path(@document), html: {:multipart => true }, :method => :put do |f| %>

  <div class="form-inputs">
    <%= f.input :upfile, as: :file, input_html: { class: 'form-control' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1> <%= "#{t('editing')} #{t('folder.folder')}" %> Editing Document</h1>

<%= render 'move_form', document: @document %>

<%= link_to t('show'), @document %> |
<%= link_to t('back'), documents_path %>

app/views/documents/index.html.erb
<h1><%= t('document.documents') %></h1>

<table>
  <thead>
    <tr>
      <th> <%= t('document.name') %> </th>
      <th><%= t('document.size') %></th>
      <th><%= t('document.version') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%=number_to_human_size document.size %></td>
        <td><%= document.version %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1> <%= "#{t('new_m')} #{t('document.document')}" %> </h1>

<%= render 'form', document: @document %>

<%= link_to t('back'), documents_path %>

app/views/documents/show.html.erb
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= "#{Version.model_name.human} #{@document.version}" %>
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <% @document.available_versions.each do |version| %>
      <a class="dropdown-item" href="<%= document_path(@document, :version=>version) %>"><%= "#{Version.model_name.human} #{version}" %></a>
    <% end %>
  </div>
</div>
<br>
<p>
  <strong><%= Document.human_attribute_name('name') %>:</strong>
  <%= @document.name %>
</p>

<p>
  <strong><%= Document.human_attribute_name('size') %>:</strong>
  <%= number_to_human_size @document.size %>
</p>

<p>
  <strong>Version:</strong>
  <%= @document.version %>
</p>
<p>
  <%= link_to t('download'), @document.access_url %>
</p>
<div>
  <%= link_to "#{t('upload')} #{t('new')} #{t('version')}", upgrade_document_path(@document) , html_options={class: 'btn btn-primary '} %>
  <%= link_to "#{t('move')} #{t('to')} #{t('new')} #{t('folder.folder')}", edit_document_path(@document) , html_options={class: 'btn btn-primary '} %>
  <%= link_to t('destroy'), @document, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger ' %>
</div>
<br>
<%= link_to t('editing'), edit_document_path(@document) %> |
<%= link_to t('back'), documents_path %>

app/views/documents/upgrade.html.erb
<h1> <%= "#{t('editing')} #{t('document.document')}" %> </h1>

<%= render 'upgrade_form', document: @document %>

<%= link_to t('show'), @document %> |
<%= link_to t('back'), documents_path %>